name: isp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - wheel
  - setuptools
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - bcrypt==4.2.1
      - cachetools==5.5.0
      - cartopy==0.23.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cryptography==44.0.0
      - cycler==0.12.1
      - cython==3.0.11
      - decorator==5.1.1
      - deprecated==1.2.15
      - dill==0.3.9
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - future==1.0.0
      - gast==0.6.0
      - google-auth==2.37.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - h5py==3.12.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - karney==1.0.10
      - keras==2.15.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.8.4
      - ml-dtypes==0.3.2
      - nitime==0.11
      - numba==0.60.0
      - numpy==1.26.4
      - nvector==1.0.1
      - oauthlib==3.2.2
      - obspy==1.4.1
      - obspyh5==0.6.0
      - opt-einsum==3.4.0
      - owslib==0.31.0
      - packaging==24.2
      - pandas==2.1.4
      - paramiko==3.5.0
      - pillow==11.1.0
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pymysql==1.1.1
      - pynacl==1.5.0
      - pyparsing==3.2.1
      - pyproj==3.6.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.16.1
      - pysftp==0.2.9
      - pyshp==2.3.1
      - python-dateutil==2.8.2
      - pytz==2024.2
      - pywavelets==1.6.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scipy==1.11.4
      - shapely==2.0.6
      - six==1.17.0
      - sourcespec==1.7
      - sqlalchemy==1.4.54
      - surfquake==0.1.7
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - tzlocal==5.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.14.1
      - zipp==3.21.0