C+
	SUBROUTINE MYLABL(XORG,YORG,AXLEN,HEIGHT,ANGLE,LABELC,NL)
C
C	  where AXLEN is the length of the axis the label is to be
C	  centered on, and XORG, YORG are the coordinates of the 
C	  start of the axis.
C-
	character*256 labelc
	XCEN = XORG + 0.5*AXLEN*COS(ANGLE/57.29578)
	YCEN = YORG + 0.5*AXLEN*SIN(ANGLE/57.29578)
	IF (NL .LE. 0) RETURN
	ANGRAD = ANGLE/57.29578
	IF (labelc(1:1) .EQ. ' ' .AND. NL .EQ. 1) RETURN
	CALL LENGTH(ALEN,HEIGHT,labelc(1:nl),NL)
	XSTART = XCEN - 0.5*ALEN*COS(ANGRAD)
	YSTART = YCEN - 0.5*ALEN*SIN(ANGRAD)
	J = 1
	JNOBL = 0
	DO WHILE ((J.LE.NL) .AND. (JNOBL.EQ.0))
	  IF (LABELC(J:J) .NE. ' ') JNOBL = J
	  J = J + 1
	END DO
	IF (JNOBL .EQ. 0) RETURN
	NLEFT = NL - JNOBL + 1
	CALL SYMBOL(XSTART,YSTART,HEIGHT,LABELC(JNOBL:NLEFT),
     1		ANGLE,NLEFT)
	CALL TSEND
	RETURN
	END
