C+
	SUBROUTINE PLOT(X,Y,IPEN)
C
C		PLOT IS CALLED TO GENERATE A PEN MOVE FROM THE CURRENT POSITION
C	TO A NEW (SPECIFIED) X/Y POSITION. THE MOVEMENT OF THE 'PEN' MAY BE
C	MADE WITH A LINE EITHER DRAWN OR NOT DRAWN, DEPENDING ON THE VALUE OF
C	'IPEN'. A NEW ORIGIN MAY BE DEFINED BY SETTING THE VALUE OF 'IPEN'
C	NEGATIVE.
C
C	CALLING SEQUENCE VARIABLES:
C	X	NEW X-COORDINATE IN INCHES RELATIVE TO CURRENT ORIGIN
C	Y	NEW Y-COORDINATE IN INCHES RELATIVE TO CURRENT ORIGIN
C	IPEN	DETERMINES MODE OF 'PEN' (LINE) MOTION
C		+/- 2	MOVE FROM PREVIOUS POINT TO NEW X,Y  'PEN DOWN'
C		+/- 3	MOVE FROM PREVIOUS POINT TO NEW X,Y 'PEN UP'
C		+N	LEAVE ORIGIN AS PREVIOUSLY DEFINED
C		-N	DEFINE NEW ORIGIN AS ENDPOINT OF THIS VECTOR
C	IF 3 < IPEN < 999 THIS IS A CALL FOR NEWPEN
C	IF IPEN = 0 THIS WOULD CLOSE A BUFFER (FOR THE HP) SO NO ACTION
C
C	CALLS PLOT FOR
C	   (3) DISKFILE ONLY
C
C	sun version:  jas/vtso 3 September 1991
C	15 June 1992:  Latest perturbation
C	3 January 2003:  Leaving out graphics terminal option.
C-
        common /jasplot/  jplot,jdummy
	if (jplot .le. 0) then
	  write(*,*) 'Have not opened plot file'
	  stop
	end if
      if (JPLOT .ge. 2) CALL PLOTDF(X,Y,IPEN)
      END
